### ISSUE TITLE
Using QuickChat with a Ajaxified Theme

### ISSUE THREAD

**Issue by rjacks** [Marko-M/quick-chat#1]
Hi,  I am having a problem using the QuickChat plugin with the Themeforest MusicPlay theme.  This theme has a fixed music player across the bottom of all pages.  In order to keep the player from stopping on page loads the theme uses AJAX to load them.  This causes a problem where the QuickChat plugin just sits there with the message 'LOADING..' after a page load.  If I turn off the theme's AJAX page loading then the plugin works as it should.  Is there any way to modify the plugin so that the init functions do not use AJAX?  Thanks for your help!

Rodney

**Comment by Marko-M** [comment]
Hello rjacks,
more definitely there is but this is so specific that I can not provide any useful information.
